# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0002_auto_20161115_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Amount', max_length=255)),
                ('multiplier', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='name2',
        ),
        migrations.AlterField(
            model_name='food',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtracker.Amount'),
        ),
        migrations.AlterField(
            model_name='log',
            name='dishes',
            field=models.ManyToManyField(blank=True, null=True, to='foodtracker.Dish'),
        ),
        migrations.AlterField(
            model_name='log',
            name='foods',
            field=models.ManyToManyField(blank=True, null=True, to='foodtracker.Food'),
        ),
    ]
