# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0005_remove_food_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
